### ISSUE TITLE
Scope overlay styling to just about dialog

### ISSUE THREAD

**Issue by job13er** [ciena-frost/ember-frost-about-dialog#23]
Currently, the following style:
https://github.com/ciena-frost/ember-frost-about-dialog/blob/master/addon/styles/addon.scss#L6-L11

Is applied to the shared `.remodal-overlay` causing _all_ modals to have that styling on their overlays. This is not the desired behavior.

**Comment by notmessenger** [comment]
This repository is deprecated so this will not be addressed.
